runtime: python39
entrypoint: python app.py

handlers:
- url: /dist
  static_dir: Front/dist
- url: /.*\.(js|css|png|jpg|jpeg|svg|json|ico)
  static_files: Front/src/\1
  upload: Front/src/.*\.(js|jsx|css|png|jpg|jpeg|svg|json|ico)$
- url: /(.*)
  static_files: Front/index.html
  upload: Front/index.html

env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: 'secreto'
  SESSION_COOKIE_SECURE: True
  REMEMBER_COOKIE_SECURE: True

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
