runtime: python311
entrypoint: python3 -m backend.app

handlers:
- url: /(.*\.(js|jsx|css|png|jpg|jpeg|svg|json|ico))$
  static_files: Front/\1
  upload: Front/.*\.(js|jsx|css|png|jpg|jpeg|svg|json|ico)$
  mime_type: text/javascript

- url: /(.*\.(css|png|jpg|jpeg|svg|gif|ico|json))$
  static_files: Front/public/\1
  upload: Front/public/.*\.(css|png|jpg|jpeg|svg|gif|ico|json)$

- url: /.*
  static_dir: Front/public

- url: /.*
  static_dir: Front/src
# Handler for the main HTML entry point
- url: /
  static_files: Front/index.html
  upload: Front/index.html

env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: 'secreto'
  SESSION_COOKIE_SECURE: True
  REMEMBER_COOKIE_SECURE: True

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
