runtime: python39
entrypoint: python app.py

handlers:
# Handler for static resources in the public folder
- url: /public
  static_dir: Front/public

# Handler for JavaScript, CSS, images, and other static files inside src
- url: /src
  static_files: Front/src/\1
  upload: Front/src/.*\.(js|jsx|css|png|jpg|jpeg|svg|json|ico)$

# Handler for the main HTML entry point
- url: /
  static_files: Front/index.html
  upload: Front/index.html

env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: 'secreto'
  SESSION_COOKIE_SECURE: True
  REMEMBER_COOKIE_SECURE: True

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
