steps:
  - name: 'python:3.11'
    entrypoint: pip
    args: ['install', '-r', 'backend/requirements.txt']

  - name: 'node:20.12.2'
    entrypoint: npm
    args: ['install', '--prefix', 'Front']

  - name: 'node:20.12.2'
    entrypoint: npm
    args: ['run', 'build', '--prefix', 'Front']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'Front', 'gs://gyminferno_static']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'backend', 'gs://gyminferno_static/backend']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'path', 'gs://gyminferno_static/path']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy', 'app.yaml', '--project=gyminferno']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy', 'app.yaml', '--project=gyminferno', '--quiet']

# Variables de entorno requeridas para los pasos
substitutions:
  _PROJECT_ID: 'gyminferno'

# Opciones para aumentar el tiempo de espera si tu compilación necesita más tiempo
timeout: '7200s'

options:
  machineType: 'E2_HIGHCPU_8'

artifacts:
  objects:
    location: 'gs://gyminferno_artifacts/'
    paths: ['Front/dist/**', 'backend/**', 'path/**']

logsBucket: 'gs://gyminferno.appspot.com'
