steps:
  - name: 'python:3.11'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  - name: 'node:20.12.2'
    entrypoint: npm
    args: ['install', '--prefix', 'Front']

  - name: 'node:20.12.2'
    entrypoint: npm
    args: ['run', 'build', '--prefix', 'Front']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'Front', 'gs://infernogym_static/Front']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'backend', 'gs://infernogym_static/backend']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', '-r', 'path', 'gs://infernogym_static/path' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy', 'app.yaml', '--project=infernogym', '--quiet']

# Variables de entorno requeridas para los paso
substitutions:
  _PROJECT_ID: 'infernogym'

# Opciones para aumentar el tiempo de espera si tu compilación necesita más tiempo
timeout: '7200s'

options:
  machineType: 'E2_HIGHCPU_8'

logsBucket: 'gs://infernogym.appspot.com'
